// <auto-generated />
using System;
using HealthAxis.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthAxis.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615082043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthAxis.API.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HealthAxis.API.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Specialisation")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            ConsultationFee = 850m,
                            FullName = "Dr Arjun Narayanan",
                            IsActive = true,
                            Specialisation = 1,
                            YearsOfExperience = 12
                        },
                        new
                        {
                            DoctorId = 2,
                            ConsultationFee = 700m,
                            FullName = "Dr Kavya Srinivasan",
                            IsActive = true,
                            Specialisation = 3,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            DoctorId = 3,
                            ConsultationFee = 1200m,
                            FullName = "Dr Rohit Menon",
                            IsActive = true,
                            Specialisation = 2,
                            YearsOfExperience = 15
                        },
                        new
                        {
                            DoctorId = 4,
                            ConsultationFee = 650m,
                            FullName = "Dr Priya Ramachandran",
                            IsActive = true,
                            Specialisation = 5,
                            YearsOfExperience = 6
                        },
                        new
                        {
                            DoctorId = 5,
                            ConsultationFee = 900m,
                            FullName = "Dr Siddharth Iyer",
                            IsActive = true,
                            Specialisation = 4,
                            YearsOfExperience = 10
                        });
                });

            modelBuilder.Entity("HealthAxis.API.Models.HealthRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RecordId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("HealthAxis.API.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("InsuranceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1998, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ananya@example.com",
                            FullName = "Ananya Krishnan",
                            Gender = 2,
                            InsuranceId = "INS1001",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            PatientId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rahul@example.com",
                            FullName = "Rahul Nair",
                            Gender = 1,
                            InsuranceId = "INS1002",
                            PhoneNumber = "9876543211"
                        });
                });

            modelBuilder.Entity("HealthAxis.API.Models.Appointment", b =>
                {
                    b.HasOne("HealthAxis.API.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthAxis.API.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthAxis.API.Models.HealthRecord", b =>
                {
                    b.HasOne("HealthAxis.API.Models.Appointment", "Appointment")
                        .WithOne("HealthRecord")
                        .HasForeignKey("HealthAxis.API.Models.HealthRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthAxis.API.Models.Doctor", null)
                        .WithMany("HealthRecords")
                        .HasForeignKey("DoctorId");

                    b.HasOne("HealthAxis.API.Models.Patient", null)
                        .WithMany("HealthRecords")
                        .HasForeignKey("PatientId");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HealthAxis.API.Models.Appointment", b =>
                {
                    b.Navigation("HealthRecord");
                });

            modelBuilder.Entity("HealthAxis.API.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HealthRecords");
                });

            modelBuilder.Entity("HealthAxis.API.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HealthRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
